name = "PaperMod"
license = "MIT"
licenselink = "https://github.com/lollek/hugo-PaperMod/blob/master/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "https://lollek.github.io/hugo-PaperMod/"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "table-of-contents",
  "highlight.js",
  "favicon",
  "archive",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.83.0"

[author]
  name = "Olle Aid Kvarnström"
  homepage = "iix.se"

[original]
  name = "PaperMod"
  author = "Aditya Telange"
  homepage = "https://github.com/adityatelange/"
  repo = "https://adityatelange.github.io/hugo-PaperMod/"
